### ISSUE TITLE
[Feature request] Selecting tag entry

### ISSUE THREAD

**Issue by kristijanhusak** [voldikss/vim-skylight#3]
Hi,

very nice plugin. I started building something like this myself, but didn't went far. This works very well.

Since i'm working on JS projects, I rely a lot on ctags. For certain things, there are multiple ctags entries. When I want to preview something, it jumps to the first tag, no matter if there are multiple entries.

How could I select a tag entry which I want to preview?

**Comment by voldikss** [comment]
Yes, I have considered this before. My solution is to open a drop-down menu at the cursor position when there are multiple results, and then move the cursor to preview different contents. Unfortunately, I recently broke my computer and have no much free time at the moment. I will look back later when I have time and get my laptop fixed.

**Comment by kristijanhusak** [comment]
Yeah something like that works. Even simple `inputlist()` would do the trick, just to allow the flexibility.

**Comment by kristijanhusak** [comment]
@voldikss I gave this a try, it works ok, but it's a bit problematic when there's a bit more entries. Selection overlaps the floating window.

Here's small example:
![screenshot](https://i.imgur.com/ijkmhD4.png)

I'd rather have an option to first select, and then let skylight show what I selected.
Or maybe show only 1 row for current file.

**Comment by voldikss** [comment]
Updated, use `:Skylight` command without `!`.

**Comment by kristijanhusak** [comment]
Awesome, thanks!
In case someone needs this, I wrote a small helper to act differently depending on the number of items. Function assumes current word is used and it checks only tags:

```vim
function! s:run_skylight() abort
  if len(taglist(expand('<cword>'))) > 2
	Skylight
  else
    Skylight!
  endif
endfunction
```

**Comment by voldikss** [comment]
Do you think it's a good behavior if I make `:Skylight` preview right away if there is only one entry?

**Comment by kristijanhusak** [comment]
Yeah i think that would be good.
