### ISSUE TITLE
Doesn't highlight types, only functions

### ISSUE THREAD

**Issue by oblitum** [voldikss/vim-skylight#4]
The highlighting feature is really nice but it seems to work only for functions. Tested on Rust code. It shows definition for types, no problem, except for lack of highlight.

**Comment by voldikss** [comment]
Sorry but this is impossible. What's highlighted is just the line, regardless of whether it is a type or function. Sometimes it cannot determine whether it's a type or function from the tag info.

**Comment by oblitum** [comment]
Okay.
