### ISSUE TITLE
Stopped working after commit latest refactor

### ISSUE THREAD

**Issue by kristijanhusak** [voldikss/vim-skylight#7]
Hi,

today I updated plugins and noticed that this stopped working.

I noticed that command changed from `:SkylightPreview` to `:Skylight word`, but even that is not working at this moment.

I tried this:
```
:Skylight TagEntry
```
But nothing happens.
When I go to any commit before 828fc838cf654031bc6a4f2c20b5134926c0decf everything works fine.

**Comment by voldikss** [comment]
Try

```vim
:Skylight tag
```

**Comment by kristijanhusak** [comment]
Yeah that works, thanks.

I was a bit confused because docs say `[file|tag|word]`, and I tried entering my word/tag that I want to search.
